### ISSUE TITLE
`type 'string' is not assignable to type 'number'` in app.js

### ISSUE THREAD

**Issue by mateiacd** [Microsoft/visualstudio-docs#104]
Hi Andres,

In your article
http://avillenas.com/post/installing-jshint-and-jscs-in-visual-studio-code

What settings have you made to get the error below in your `app.js` file ?
`type 'string' is not assignable to type 'number'`

JSHint and JSCS do not show this error on my computer ?

This looks more like a tsc compiler error but how did you make it to work on app.js ?
(because the TypeScript compiler works with .ts files)

Please give details, thank you.

**Comment by gregvanl** [comment]
Hi @mateiacd. This repo is for Visual Studio documentation issues, not Visual Studio Code or any of it's extensions. You might try contacting Andres through a comment on his blog.
