### ISSUE TITLE
Ctrl X and Ctrl Y Not Work :D

### ISSUE THREAD

**Issue by domainmurat** [Microsoft/visualstudio-docs#115]
Hi;

When I working with debug, Ctrl X and Ctrl Y operations broke my html codes, that's interesting.

**Comment by gregvanl** [comment]
Hi @domainmurat, This repository is for the Visual Studio online documentation. I believe you wish to report a Visual Studio product issue. If so, please see [How to report a problem with Visual Studio 2017](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017).
