### ISSUE TITLE
Broken link in test/improve-code-quality.md

### ISSUE THREAD

**Issue by RobDesideri** [Microsoft/visualstudio-docs#15]
In `test/improve-code-quality.md` there is a link to `test/test-apps-early-and-often.md` at anchor `[Testing the application]`.
But the `test/test-apps-early-and-often.md` file not exists.

**Comment by gregvanl** [comment]
Fixed with https://github.com/Microsoft/vsdocs/pull/164/commits/f957af4ed01cba349a84d4c58d28b821e8565092
Thank you for logging the issue.
