### ISSUE TITLE
Code examples are hidden in the website

### ISSUE THREAD

**Issue by srayuws** [Microsoft/visualstudio-docs#29]
Code examples are hidden in the website.

Example: 
The `Syntax` part are hidden on [docs.microsoft.com](https://docs.microsoft.com/en-us/visualstudio/msbuild/item-element-msbuild), but can be seen on [github.com](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/msbuild/item-element-msbuild.md), also the `Example` part is not shown in the web UI.

**Comment by Mikejo5000** [comment]
A known issue around this has been fixed. If you have a repro and still see a problem, let us know.
