### ISSUE TITLE
Creating offline installer, includeRecommended/includeOptional switches doen't work

### ISSUE THREAD

**Issue by dehghani-mehdi** [Microsoft/visualstudio-docs#69]
Hi,

Based on documentation, I tired to create an offline installer of VS 2017 using:
`vs_enterprise.exe --layout --lang en-US --add Microsoft.VisualStudio.Workload.CoreEditor Microsoft.VisualStudio.Workload.NetCoreTools Microsoft.VisualStudio.Workload.NetCrossPlat Microsoft.VisualStudio.Workload.NetWeb Microsoft.VisualStudio.Workload.WebCrossPlat Microsoft.VisualStudio.Workload.Node` , its worked (I downloaded about 3GB), then I added `includeRecommended/includeOptional` switches to download some additional packages for some workloads, but doesn't work. I tired following commands:

- `vs_enterprise.exe --layout --lang en-US --add Microsoft.VisualStudio.Workload.NetCoreTools --includeRecommended`
- `vs_enterprise.exe --layout --lang en-US --includeRecommended --add Microsoft.VisualStudio.Workload.NetCoreTools`
- ... (I mean I changed order of all parameters, actually I tired all possible options)

I tired that to new (empty) folder, but no success.

Content of `dd_bootstrapper_20170402115915.log`

> Beginning of the log. Start Time: 4/2/2017 11:59:15 AM
VisualStudio Bootstrapper:4/2/2017 11:59:16 AM: Current OptIn value is 1
VisualStudio Bootstrapper:4/2/2017 11:59:16 AM: Commandline arguments = --layout --lang en-US --add Microsoft.VisualStudio.Workload.NetWeb --includeRecommended --includeOptional
VisualStudio Bootstrapper:4/2/2017 11:59:19 AM: Parent process name = vs_Enterprise
VisualStudio Bootstrapper:4/2/2017 11:59:19 AM: Parent process product version = 15.0.26228.0
VisualStudio Bootstrapper:4/2/2017 11:59:19 AM: CampaignId = 
VisualStudio Bootstrapper:4/2/2017 11:59:20 AM: DownloadURL = https://aka.ms/vs/15/release/installer
VisualStudio Bootstrapper:4/2/2017 11:59:20 AM: InstallLocation = C:\Program Files (x86)\Microsoft Visual Studio\Installer
VisualStudio Bootstrapper:4/2/2017 11:59:20 AM: OfflineFilePath = E:\v\vs_installer.opc
VisualStudio Bootstrapper:4/2/2017 11:59:20 AM: LayoutLocation = E:\v
VisualStudio Bootstrapper:4/2/2017 11:59:20 AM: ExecutableArguments =  layout --bootstrapperPath "E:\v\vs_Enterprise.exe" --layout "E:\v" --layoutPath "E:\v" --in "C:\ProgramData\Microsoft\VisualStudio\Packages\_bootstrapper\vs_setup_bootstrapper.json" --lang en-US --add Microsoft.VisualStudio.Workload.NetWeb --includeRecommended --includeOptional --locale en-US --activityId "07a6ae19-b816-4459-b1e1-74c8754438c0"
VisualStudio Bootstrapper:4/2/2017 11:59:20 AM: OSVersion = Microsoft Windows NT 10.0.14393.0
VisualStudio Bootstrapper:4/2/2017 11:59:21 AM: Using Offline package: E:\v\vs_installer.opc
VisualStudio Bootstrapper:4/2/2017 11:59:21 AM: Verifying signature
VisualStudio Bootstrapper:4/2/2017 11:59:24 AM: Beginning extracting files to E:\v\1.dnh.
VisualStudio Bootstrapper:4/2/2017 11:59:24 AM: Extracting vs_installer.opc to 'E:\v\1.dnh'.
VisualStudio Bootstrapper:4/2/2017 11:59:27 AM: Successfully extracted 'E:\v\1.dnh'.
VisualStudio Bootstrapper:4/2/2017 11:59:27 AM: Starting vs setup process 'setup.exe' with arguments ' layout --bootstrapperPath "E:\v\vs_Enterprise.exe" --layout "E:\v" --layoutPath "E:\v" --in "C:\ProgramData\Microsoft\VisualStudio\Packages\_bootstrapper\vs_setup_bootstrapper.json" --lang en-US --add Microsoft.VisualStudio.Workload.NetWeb --includeRecommended --includeOptional --locale en-US --activityId "07a6ae19-b816-4459-b1e1-74c8754438c0" --InstallerPath "E:\v\1.dnh\vs_installer.opc"'.
VisualStudio Bootstrapper:4/2/2017 11:59:27 AM: Unable to parse the json file since it not exists: 0
VisualStudio Bootstrapper:4/2/2017 11:59:27 AM: Vs setup process E:\v\1.dnh\resources\app\layout\setup.exe started. All done.
VisualStudio Bootstrapper:4/2/2017 11:59:27 AM: Waiting for setup process to complete...
VisualStudio Bootstrapper:4/2/2017 11:59:28 AM: Vs setup process exited with code 87
VisualStudio Bootstrapper:4/2/2017 11:59:28 AM: Bootstrapper Successfully completed.

And `dd_vs_Enterprise_decompression_log.txt`

>[4/2/2017, 11:59:13] === Logging started: 2017/04/02 11:59:13 ===
[4/2/2017, 11:59:13] Executable: E:\v\vs_Enterprise.exe v15.0.26228.0
[4/2/2017, 11:59:13] --- logging level: standard ---
[4/2/2017, 11:59:13] Directory 'C:\Users\Mehdi\AppData\Local\Temp\aa3214a2023fa44ec65cec\' has been selected for file extraction
[4/2/2017, 11:59:13] Extracting files to: C:\Users\Mehdi\AppData\Local\Temp\aa3214a2023fa44ec65cec\
[4/2/2017, 11:59:14] Extraction took 375 milliseconds
[4/2/2017, 11:59:14] Executing extracted package: 'vs_bootstrapper_d15\vs_setup_bootstrapper.exe ' with commandline '  --layout --lang en-US --add Microsoft.VisualStudio.Workload.NetWeb --includeRecommended --includeOptional'
[4/2/2017, 11:59:29] The entire Box execution exiting with result code: 0x0
[4/2/2017, 11:59:29] Launched extracted application exiting with result code: 0x57
[4/2/2017, 11:59:29] === Logging stopped: 2017/04/02 11:59:29 ===

Can you please help me on this?, thanks.

**Comment by timsneath** [comment]
Hi there - we had a bug here but it should be fixed in the 15.1 release, which we published yesterday. Can you try the updated version? Sorry for the inconvenience!

**Comment by dehghani-mehdi** [comment]
@timsneath don't worry, thanks for the answer. I just tired with new version (with 1 workload for now) & seems you fixed the issue.
I close the issue, I'll post here if it doesn't work as I expect.

Thanks again.

**Comment by dehghani-mehdi** [comment]
@timsneath I'm sorry to post again, 2 days ago, I tired `vs_enterprise.exe --layout --lang en-US --add Microsoft.VisualStudio.Workload.NetWeb --includeRecommended --includeOptional`, and woked, then I closed the issue. today to decided to add more workloads, but the issue occurred.

I tired `vs_enterprise.exe --layout --lang en-US --add Microsoft.VisualStudio.Component.CoreEditor`, even `vs_Enterprise.exe --layout` doesn't work for me. Can you please help me on this?

**Comment by timsneath** [comment]
Oh, you need to specify a folder with the `--layout` command. For example, try the following:
```
vs_enterprise --layout c:\vs2017 --lang en-US --add Microsoft.VisualStudio.Workload.CoreEditor
```

**Comment by dehghani-mehdi** [comment]
Thanks, but I tired `vs_enterprise.exe --layout e:\vs2017 --lang en-US --add Microsoft.VisualStudio.Workload.CoreEditor` before posting here, the folder created by installer including `certificates` folder & `vs_installer.version.json` file.

**Comment by timsneath** [comment]
OK - that sounds like it worked though if it created those folders? Can you help me understand the difference between what you expected to happen and what actually happened?

**Comment by dehghani-mehdi** [comment]
I expected to download files, based on mentioned component(s)/workload(s), (_fox ex. when I run `vs_enterprise.exe --layout e:\vs2017 --lang en-US --add Microsoft.VisualStudio.Workload.NetWeb --includeRecommended --includeOptional`, I expected the installer download all files of this workload and store them_), but when I run the command, installer create `vs2017` folder, _including certificates folder & vs_installer.version.json file_, but doesn't download anything else, in fact the cmd disappear immediately (the second one, that show download progress).

I don't why, but even before opening this issue, I was able to download with `vs_enterprise.exe --layout` command, but now I can not. is it possible to installer store some file/log somewhere _in my PC_, so now it think I downloaded all of files? (actually I downloaded all of `Microsoft.VisualStudio.Workload.NetWeb` already, _when I closed this issue, after your first answer_)

**Comment by timsneath** [comment]
Ah, OK - sorry, I didn't realize that _only_ those files had been downloaded. The logs are stored in the %temp% directory. Perhaps you could do me a favor and run `http://aka.ms/vscollect.exe` and upload `%TEMP%\vslogs.zip` somewhere where I can have a look?

**Comment by dehghani-mehdi** [comment]
@timsneath I got the cause of problem. first time that I run the command and that was successful, the installer downloaded `vs_installer.opc` & putted that on next of `vs_enterprise.exe`, seems like each time that I want to download new items, I have to remove this file. so installer downloaded that again, I don't know its a bug or not, but that's the problem.

Many thanks for your time and support.
